import type { WorkerProfile } from '@/lib/types';

export const demoWorkers: WorkerProfile[] = [
  { id:'W-001', caseId:'CASE-0009', name:'سعيد الطاهر', nationality:'مصري', phone:'0911111109', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-05-02', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'شركة مقاولات', receivedServices:['إقامة','فتح حساب مصرفي'], activeServices:['شريحة هاتف'], legalNotes:'لا توجد ملاحظات', lastUpdated:'2026-05-06' },
  { id:'W-002', caseId:'CASE-0016', name:'جمال فضل', nationality:'سوداني', phone:'0911111116', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-05-03', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'مطعم المدينة', receivedServices:['إقامة'], activeServices:['سكن عمالي'], legalNotes:'متابعة عقد التشغيل', lastUpdated:'2026-05-05' },
  { id:'W-003', caseId:'CASE-0018', name:'إبراهيم خان', nationality:'باكستاني', phone:'0911111118', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-05-04', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'ورشة النور', receivedServices:['إقامة','شريحة هاتف'], activeServices:['رخصة قيادة'], legalNotes:'يحتاج نسخة جواز محدثة', lastUpdated:'2026-05-04' },
  { id:'W-004', name:'محمد حسن', nationality:'مصري', phone:'0922222201', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-04-26', sponsorCompany:'شركة اليسر', workplace:'شركة البناء الحديث', receivedServices:['إقامة'], activeServices:['فتح حساب مصرفي','شريحة هاتف'], legalNotes:'جاهز لخدمات إضافية', lastUpdated:'2026-05-06' },
  { id:'W-005', name:'آدم سليمان', nationality:'تشادي', phone:'0922222202', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-04-20', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'مخزن مواد غذائية', receivedServices:['إقامة'], activeServices:['سكن عمالي'], legalNotes:'لا توجد', lastUpdated:'2026-05-03' },
  { id:'W-006', name:'مصطفى رحمان', nationality:'بنغلاديشي', phone:'0922222203', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-04-18', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'شركة تنظيف', receivedServices:['إقامة','سكن'], activeServices:['رخصة قيادة'], legalNotes:'متابعة وثيقة السكن', lastUpdated:'2026-05-01' },
  { id:'W-007', name:'خالد عمر', nationality:'سوري', phone:'0922222204', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-04-12', sponsorCompany:'شركة الأمان', workplace:'مكتب خدمات', receivedServices:['إقامة'], activeServices:['حجز تذكرة'], legalNotes:'طلب سفر قريب', lastUpdated:'2026-04-29' },
  { id:'W-008', name:'عبد الرحمن صالح', nationality:'باكستاني', phone:'0922222205', residencyStatus:'الإقامة مكتملة', residencyCompletedAt:'2026-04-09', sponsorCompany:'الإقامة الليبية الآمنة', workplace:'ورشة ميكانيكا', receivedServices:['إقامة','شريحة'], activeServices:[], legalNotes:'لا توجد', lastUpdated:'2026-04-28' },
];
